name: iOS CI

on: [push, pull_request]

jobs:
  ios-tests:
    name: Build and Test (iOS Simulator)
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Build and Test (auto-detect project/workspace)
        shell: bash
        run: |
          set -euo pipefail
          echo "Xcode version:"
          xcodebuild -version

          # Select a real, available iPhone simulator by UDID (avoid name/OS mismatch)
          UDID=$(xcrun simctl list devices available -j | python3 - <<'PY' || true
import sys, json
data = json.load(sys.stdin)
udid = None
for runtime, devices in (data.get('devices') or {}).items():
    if not runtime.startswith('com.apple.CoreSimulator.SimRuntime.iOS'):
        continue
    for d in devices:
        if d.get('isAvailable') and 'iPhone' in d.get('name',''):
            udid = d.get('udid')
            break
    if udid:
        break
if udid:
    print(udid)
PY
          )
          if [ -z "$UDID" ]; then
            echo "No available iOS iPhone simulator found; skipping tests."
            echo "Hint: Set IOS_SCHEME and ensure simulator runtimes are installed."
            exit 0
          fi
          DESTINATION="platform=iOS Simulator,id=$UDID"

          # Detect workspace or project using BSD find (no -quit on macOS)
          WORKSPACE=$(find . -type d -name "*.xcworkspace" | head -n 1 | sed 's|^./||')
          PROJECT=$(find . -type d -name "*.xcodeproj" | head -n 1 | sed 's|^./||')

          if [ -n "$WORKSPACE" ]; then
            if [ -z "${IOS_SCHEME:-}" ]; then
              SCHEME=$(xcodebuild -list -json -workspace "$WORKSPACE" | python3 - <<'PY'
import sys, json
d=json.load(sys.stdin)
w=d.get('workspace') or d.get('project') or {}
schemes=w.get('schemes') or []
print(schemes[0] if schemes else '', end='')
PY
              )
            else
              SCHEME="$IOS_SCHEME"
            fi
            if [ -z "$SCHEME" ]; then
              echo "No scheme found in workspace $WORKSPACE" >&2
              exit 1
            fi
            echo "Using workspace: $WORKSPACE"
            echo "Using scheme: $SCHEME"
            xcodebuild clean test \
              -workspace "$WORKSPACE" \
              -scheme "$SCHEME" \
              -destination "$DESTINATION" \
              CODE_SIGNING_ALLOWED=NO
          elif [ -n "$PROJECT" ]; then
            if [ -z "${IOS_SCHEME:-}" ]; then
              SCHEME=$(xcodebuild -list -json -project "$PROJECT" | python3 - <<'PY'
import sys, json
d=json.load(sys.stdin)
p=d.get('project') or {}
schemes=p.get('schemes') or []
print(schemes[0] if schemes else '', end='')
PY
              )
            else
              SCHEME="$IOS_SCHEME"
            fi
            if [ -z "$SCHEME" ]; then
              echo "No scheme found in project $PROJECT" >&2
              exit 1
            fi
            echo "Using project: $PROJECT"
            echo "Using scheme: $SCHEME"
            xcodebuild clean test \
              -project "$PROJECT" \
              -scheme "$SCHEME" \
              -destination "$DESTINATION" \
              CODE_SIGNING_ALLOWED=NO
          else
            echo "No .xcworkspace or .xcodeproj found; nothing to test."
            exit 0
          fi

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ios-test-results
          path: |
            **/*.xcresult
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcactivitylog
          if-no-files-found: ignore
