name: CI

on: [push, pull_request]

jobs:
  check:
    name: Basic CI
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify
        run: echo "CI is green"
