name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test iOS App
    runs-on: macos-14
    timeout-minutes: 30
    strategy:
      matrix:
        simulator: ["iPhone 16"]
        ios-version: ["17.4"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      - name: Verify Xcode Version
        run: |
          xcode_version=$(xcodebuild -version | grep Xcode | awk '{print $2}')
          echo "Selected Xcode version: $xcode_version"
          if ! [[ "$xcode_version" =~ ^15\..* ]]; then
            echo "Error: Expected Xcode 15.x, but got $xcode_version" >&2
            exit 1
          fi

      - name: List Available Simulators
        run: |
          echo "Available simulators:"
          xcrun simctl list devices available

      - name: Build and Test
        run: |
          xcodebuild clean test \
            -project lcc.xcodeproj \
            -scheme lcc \
            -destination "platform=iOS Simulator,name=${{ matrix.simulator }},OS=${{ matrix.ios-version }}" \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.simulator }}-${{ matrix.ios-version }}
          path: |
            **/*.xcresult
            ~/Library/Developer/Xcode/DerivedData/**/Logs/Test/*.xcactivitylog
